### ISSUE TITLE
Mongodb connectivity 

### ISSUE THREAD

**Issue by ghost** [ShankyTiwari/Sending-message-to-specific-user-with-socket.io#1]
Can you explain how to make mongodb connection to this chat?

**Comment by ShankyTiwari** [comment]
Hey @AqsaKh ,

I have already written an article on this, you can read these article with respect to your favorite framework,

 **AngularJS =>** https://www.codershood.info/2015/12/10/real-time-chatting-app-using-nodejs-mysql-angularjs-and-socket-io-part-1/

**Angular =>** https://www.codershood.info/2017/02/09/real-time-private-chatting-app-using-angular-2-nodejs-mongodb-socket-io-part-1/

**React =>** https://www.codershood.info/2019/03/31/real-time-private-chatting-app-using-react-nodejs-mongodb-and-socket-io-part-1/
